apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: $(FLUENTD_NAMESPACE)
  labels:
    k8s-app: fluentd-cloudwatch
data:
  logs.region: $(AWS_REGION)
  cluster.name: $(CLUSTER_NAME)
  kubernetes.conf: |
    kubernetes.conf
  fluent.conf: |
    @include containers.conf

    <match fluent.**>
      @type null
    </match>
  containers.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match **service-a**>
      @type cloudwatch_logs
      region $(AWS_REGION)
      log_group_name $(LOG_GROUP_NAME)
      log_stream_name $(A_LOG_STREAM_NAME)
      auto_create_stream true
      <buffer>
        flush_thread_count 8
        flush_interval 1
        chunk_limit_size 2M
        queue_limit_length 32
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>
    <match **service-b**>
      @type cloudwatch_logs
      region $(AWS_REGION)
      log_group_name $(LOG_GROUP_NAME)
      log_stream_name $(B_LOG_STREAM_NAME)
      auto_create_stream true
      <buffer>
        flush_thread_count 8
        flush_interval 1
        chunk_limit_size 2M
        queue_limit_length 32
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>
    <match **service-c**>
      @type cloudwatch_logs
      region $(AWS_REGION)
      log_group_name $(LOG_GROUP_NAME)
      log_stream_name $(C_LOG_STREAM_NAME)
      auto_create_stream true
      <buffer>
        flush_thread_count 8
        flush_interval 1
        chunk_limit_size 2M
        queue_limit_length 32
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>