apiVersion: v1
kind: ConfigMap
metadata:
  name: service-c-fluent-bit-config
  namespace: $(APP_NAMESPACE)
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /log/app.log
        Parser        container
        Tag           service-c.*
    
    [FILTER]
        Name          kubernetes
        Match         service-c.*
        Kube_URL      https://kubernetes.default.svc.cluster.local:443
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Merge_Log     On
        Keep_Log      Off

    [OUTPUT]
        Name          forward
        Match         service-c.*
        Host          fluentd-svc.fluentd.svc.cluster.local
        Port          24224
  parsers.conf: |
    [PARSER]
        Name         container
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    Off
        Decode_Field_As json log